.travis.yml:
  sudo: true
  services:
    - docker
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
  deploy:
    access_key_id: AKIAINMB43VSSPFZISAA
    secret_access_key:
      secure: gYSfVlcFmPyj06vf368gEplA11ytGsqbyjKNWEvOdWLEXca9q7LsOtstwZVhUyAmZxUyyvWPs/cPVskCscZEA/rvb78BQKgPLaac9elgF4gnxUzh21xpwfXMMefTIsELa9/izzrQYmov/+CLFHvkj1iSIolf/aC4xsYWTEDioadexrZFYpgMkCp6PHZi6OklBImdV0lDhUxOeXneqG1KfNg3bm6SN2VAZnxDbW2pM86b7jA6DN9RNqR4VJKsi2A0gYDiW4P2Cx7niXn6RABeXj1yeHb/GYFtbh7nuMcGnOGOIBSpPAXah5O7VM47cmKYa2cw4wbRB87XDM7goKw//ZFB4MtWsWeLmAkhiVKBt6p5EvkQFonkA6I6NIM7+bFHqRQ3gzqpK31KIgiBdEOAdR/Fsbzpb7qya7KeFr5DjJK5V5ik14M/Br9QpBptZLaIfn9xzQ2iObRKZNCF1qjkcX9lz0tLN/saDW4XfEqLq4cvlp1jCR7KXc+65dA7yMkByA/D8HKUm/IXg5JyeiF4pWeM3OamJCeIj6oD/3HEe5Y+VzMl5OE81e5YU6eqNTrCwAzvzE60S/5O7muKcTEthc6C8+5Cxq9REt6+t8zrEpLl1ZTe2kAVPcUweBli+OrBptLQDZQFrrQDUUnWcQ4r/IteHN5CPomHbtUMuBOQgKk=
    api_key:
      secure: LO+2If9Yd3fTngevlQ1ICFCOqv2UKx8XVhmtFaOlu5+3QEpEjq/DcmE7MlX2WzT+VjJsu4YBlf2UtkfAgIS4dOoR8FPn9M7nFiH7surzULm2MD0FWrQR+rWBn5xXC80Qrr6npi53DrWRlnSMgVNytRrnpiPUXgmUag0s+dV4+Kcf55J6CypkgpZGiFKD/E4tw46UWBPdP370UKIQKQO+rvhoXFDSaM2wjoRdMEoUROHCiUqGJnXtdHwx8d6FYmZGYtt2OCbl3nwv5KUFDDVinOSDsuASoa9gX1hbZAWT0AGRozN/97E9HGIZ+1pxMK25Mgxv4M7OOnCv1LHjjPo8gW/U0nnC8WfUfbmlWb3neem/p2JAzn8CsRbgYDG6VPujuEB2Yfmwt9TqbMsxaaTQFKdGYKZp7xPIsQlGITzkeSb6XFdw1qEEtad0V8sI+oU/Cvk5a5s7TEPBAs1FcZ4BaDtYkIcL43HO1SyHgEMrfIX/2m1pJkpgbzNCMamQzWb/owZXMDOgX4fMvx+upwo2zn4uXbGV9o9Oqa/l9/czJE7EMfHCjeR9IdMULtJPdVxOBoFNqubYRIvGwVtx+K/vrIouDXUefdWGcayvfZQXw6qnQdagyDNvuuTobfF+AXiOXluSOptgBjrdpMm77lFYuDDuQ6pRWDtorKEyVIWfQTo=
